# Generated by Django 5.1.2 on 2024-10-19 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipomantenimiento',
            name='nombre',
            field=models.CharField(max_length=150),
        ),
    ]
